accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

bbs/urls.py
from .models import Article
from django.views import generic
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

motif/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/bbs/')),
    path('index.html', RedirectView.as_view(url='/bbs/')),
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

bbs/models.py
from django.db import models
from django.urls import reverse

class Article(models.Model):
    title = models.CharField(max_length = 200)
    singer = models.CharField(max_length = 200)
    composition = models.CharField(max_length = 200)
    url = models.URLField(max_length = 200)
    content = models.TextField(max_length=1000)

    author = models.ForeignKey(
        'auth.User',
        on_delete = models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('bbs:detail', kwargs={'pk': self.pk})

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

bbs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
from django.views import generic
from .article import youtubeurl

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

class IndexView(generic.ListView):
    model = Article

class DetailView(generic.DetailView):
    model = Article

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Article
    fields = ['content', 'title', 'singer', 'composition', 'url',]

    def form_valid(self, form):
        form.instance.url = youtubeurl(form.instance.url)
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Article
    fields = ['content', 'title', 'singer', 'composition', 'url',]

    def form_valid(self, form):
            form.instance.url = youtubeurl(form.instance.url)
            return super(UpdateView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()

        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')

        return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Article
    success_url = reverse_lazy('bbs:index')

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>Signup</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Signup</button>
    </form>
    <p>Loginは<a href='{% url "login" %}'>こちら</a></p>
</section>
{% endblock %}

bbs/templates/bbs/article_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}

<h1>投稿の削除</h1>
<p>以下を削除しますか?</p>
<p>曲名：{{ article.title }}</p>
<p>歌手・バンド：{{ article.singer }}</p>
<p>作曲：{{ article.composition }}</p>
<p>リンク：{{ article.url }}</p>
<p><iframe width="560" height="315" src="{{ article.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
<p>コメント：<br>{{ article.content }}</p>
<p>{{ article.author }}</p>
<p>{{ article.created_at|date:"Y-m-j H:i:s" }}<br>
{{ article.updated_at|date:"Y-m-j H:i:s" }}</p>

<form action='' method='post'>{% csrf_token %}
    <a href='JavaScript:history.back()' class='btn btn-outline-primary'>削除しないで戻る</a>
    <button type='submit' class='submit delete btn btn-danger'>削除する</button>
</form>

{% endblock %}

bbs/templates/bbs/article_detail.html
<html>
    <head>
        <title>詳細</title>
        <style type="text/css">
            body {
                width: 800px;
                height: 300px;
                background-color: #ffffff;
                background-image: url("../../static/img/kelly-sikkema-p44B3PKChs4-unsplash copy.png");
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center;
                }
            .main {
                width: 1135px;
                height: 722px;
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%,-50%);
                background-color: rgba(255,255,255,0.3);
                border-radius: 124px;
                }
                div  p{
                    width: 90%;
                    text-align: center;
                }
                .mt-4 {
                    width: 50%;
                    text-align: center;
                }
        </style>
    </head>
    <body>
        <div class='main'>
            <p>曲名：{{ article.title }}</p>
            <p>歌手・バンド：{{ article.singer }}</p>
            <p>作曲：{{ article.composition }}</p>
            <p><iframe width="560" height="315" src="{{ article.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
            <p>コメント：<br>{{ article.content }}</p>
            <p>{{ article.author }}</p>
            <p>{{ article.created_at|date:"Y-m-j H:i:s" }}<br>
            {{ article.updated_at|date:"Y-m-j H:i:s" }}</p>
        </div>
        <div class='mt-4'>
            {% if request.user.id == object.author_id %}
            <a href='{% url "bbs:update" article.pk %}' class='btn btn-outline-primary mr-2'>編集</a>
            {% endif %}

            <a href='{% url "bbs:index" %}' class='btn btn-outline-primary'>一覧に戻る</a>

            {% if request.user.id == object.author_id %}
            <a href='{% url "bbs:delete" article.pk %}' class='btn btn-danger ml-5'>削除</a>
            {% endif %}
        </div>
    </body>
</html>

bbs/templates/bbs/article_form.html
<!DOCTYPE html>
{% load widget_tweaks %}
<html>
<head>
    <style>
    body{
        background-image: url("../../static/img/tintinberonberonjulljull.png");
        background-size: cover;
        background-repeat: no-repeat;

    }
    .container {
        display: flex;
        justify-content: center;
    }
    .tinpoko {
        margin-top: 110px;
        margin-left: 28px;
        width: 700px;
        height: 550px;
        /* UI Properties */
        border: 1px solid var(--unnamed-color-707070);
        background: #FFFFFF 0% 0% no-repeat padding-box;
        border: 1px solid #707070;
        border-radius: 124px;
        opacity: 1;
    }

    .form_title {
        width: 221px;
        height: 21px;
        margin-top: -30px;
        margin-left: 300px;
        border-radius: 26px;
        border: 1px solid #707070;
    }

    
    .box {
        margin-top: 50px;
        margin-left: 100px;
    }
    .form_music {
        margin-bottom: -50px;
        margin-top: 16px;
        margin-left: 120px;
        font: normal normal normal 25px/50px Arial Black;
        font-weight: bold;
        color: black;
    }

    .form_music1 {
        margin-bottom: -50px;
        margin-top: 10px;
        margin-left: 120px;
        font: normal normal normal 25px/50px Arial Black;
        font-weight: bold;
        color: black;
    }
    /*.form_singer {
        font: normal normal normal 25px/50px Arial Black;
        font-weight: bold;
        color: black;
    }
    .form_composition {
        font: normal normal normal 25px/50px Arial Black;
        font-weight: bold;
        color: black;
    }
    .form_url {
        font: normal normal normal 25px/50px Arial Black;
        font-weight: bold;
        color: black;
    }*/
    .comment {
        font-size:  20px;
        margin-top: 30px;
        margin-left: 250px;
        width: 600px;
        height: 30px;
    }
   /*.comment_box {
    font-size:  20px;
    margin-top: -40px;
    margin-left: 350px;
    width: 600px;
    height: 30px;
   }*/

   .create {
    width: 121px;
    height: 31px;
    margin-top: 20px;
    margin-left: 490px;
    background-color: white;
    color: black;
    border-radius: 26px;
    border: 1px solid black;
   }
   .create:hover {
    background-color: #0000ff;
    color: #FFFFFF;
   }
   .form_comment {
        margin-bottom: -50px;
        margin-top: 46px;
        margin-left: 220px;
        font: normal normal normal 22px/40px Arial Black;
        font-weight: bold;
        color: black;
   }
   .form_comt {
        width: 221px;
        height: 200px;
        margin-top: 30px;
        margin-left: 400px;
        border-radius: 26px;
        border: 1px solid #707070;
    }
 
    </style>
</head>
<body>
<div class="container">
<div class="tinpoko">
<form action='' method='post'>
    {% csrf_token %}
<div class="box">
    <p class="form_music1">曲名</p>{{ form.title|add_class:'form_title' }}
    <p class="form_music">歌手・バンド</p>{{ form.singer|add_class:'form_title' }}
    <p class="form_music">作曲</p>{{ form.composition|add_class:'form_title' }}
    <p class="form_music">リンク</p>{{ form.url|add_class:'form_title' }}
</div>
    <!--<p><iframe width="560" height="315" src="{{ article.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
    -->
        <p class="form_comment">コメント</p>{{ form.content|add_class:'form_comt' }}
    <button type='submit' class='submit btn btn-outline-primary'></button><button class="create"> 作成</button>
</form>
<div class="mt-3">
 
</div>
</div>
</div>
</body>
</html>

bbs/templates/bbs/article_list.html
{% block content %}

    <!-- ここから下をいおりが編集 -->
    <link rel="stylesheet" href="../../static/bbs/css/style.css">
    <body>
        <div class="title">MOTIF</div>
    </body>

    {% if user.is_authenticated %}
    <!-- ログインしているとき -->
    <div class="box">
        <a href='{% url "logout" %}' class='login'>logout</a>
    </div>
    {% else %}
        <!-- ログインしていないとき -->
    <div class="box">
        <a href='{% url "login" %}' class='login'>login</a>
    </div>
        <p class="new_acount">登録していない方は<a class="kotira" href='{% url "accounts:signup" %}'>こちら</a></p>
    {% endif %}
    {% if user.is_authenticated %}
        <div class="box">
            <a href='{% url "bbs:create" %}'  class='create'>投稿する</a>
        </div>
    {% else %}
        <div class="box">
            <a href='{% url "login" %}'  class='create'>投稿する</a>
        </div>
    {% endif %}

    <table class='table table-striped table-hover'>
        <tr>
            <th></th>
            <th>曲名</th>
            <th>歌手・バンド</th>
            <th>投稿者</th>
            <th>コメント</th>
        </tr>
        {% for article in object_list %}
        <tr>
            {% load static %}
            <td><img src="{% static 'bbs/img/cdimg.jpg' %}" width="200" height="200"></td>
            <td>
                <h1><a href='{% url "bbs:detail" article.pk %}'>{{ article.title }}</a></h1><br>
                作成日時：{{ article.created_at|date:"Y-m-j H:i" }}<br>
                更新日時：{{ article.updated_at|date:"Y-m-j H:i" }}
            </td>
            <td>{{ article.singer }}</td>
            <td>{{ article.author }}</td>
            <td>{{ article.content }}</td>
        </tr>
        {% endfor %}
    </table>


{% endblock %}

bbs/templates/bbs/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
        <title>MOTIF</title>
    </head>
</html>

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel="stylesheet" type="text/css" href="{% static 'bbs/css/style.css' %}">
        <title>MOTIF</title>
    </head>
    <body class="login_body">
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>